# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Install EF Core tools'
  inputs:
    command: custom
    custom: tool
    arguments: 'install dotnet-ef -g'

- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs: 
    command: restore

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish dotnet'
  inputs:
    command: publish
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    includesymbols: true
    includesource: true
    

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact to drop'
  inputs:
    artifactName: 'solution'

